services:
  api:
    build: .
    container_name: filmes_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: filmes_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bcd@127
      MYSQL_DATABASE: filmes_brasil
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pbcd@127"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
